### ISSUE TITLE
Prevent from running on Master nodes

### ISSUE THREAD

**Issue by lsadehaan** [kvaps/kube-linstor#11]
Great project!
I am deploying linstor for the first time and I think I've reached almost the finish line, but now the "satellite" workload is being deployed onto all of my node's - but I only want to use the storage on my worker nodes, so I only configured them with storage. Now the Satellite workload is failing on my "master" nodes. 
Should it be running on the master nodes? and if not, how do I make it not run there?

**Comment by kvaps** [comment]
Hi, sorry, I somehow did not notice about this issue.

> the "satellite" workload is being deployed onto all of my node's

This is because tolerations. Default example yamls are containing tolerations to allow run satelites on master nodes,  you can configure any tolerations in your values.yaml

https://github.com/kvaps/kube-linstor/blob/c8d9f624df5d4525fe4d29d6851e944fc68d34dc/examples/linstor.yaml#L17-L22

or replace them to `tolerations: []` if you don't need any
