### ISSUE TITLE
Design best practices for production

### ISSUE THREAD

**Issue by jbanety** [kvaps/kube-linstor#20]
Hi @kvaps,

I'm wondering how to deploy linstor with packages on a new cluster.
I have 2 masters/controllers and 3 workers nodes.

In your examples, you tolerate to deploy on masters. Is this a best practice for production ?
Can you describe the best way to do it ? 

Thanks for your great work.

**Comment by kvaps** [comment]
Hello, I was usually considering LINSTOR as part of Kubernetes control-plane because it is directly responsible for all the storage in the cluster.
For that reason I was deploying it on the same master nodes.

But example is just an example, you can use any nodes which you want, however it's better to place stolon or etcd volumes on the nodes which will not change according the time.
All the rest components are stateless, so you can change them at any time.

**Comment by jbanety** [comment]
OK.
Have you ever deals with storage only nodes with linstor?

**Comment by kvaps** [comment]
Well, we use both approaches, with storage nodes together or separated from the main workload, both are working fine.

When storage nodes are separated it suppose to be easier for update, however you still need to update client nodes as well.

Don't forget about it😉

**Comment by jbanety** [comment]
Thanks.
